//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseHub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CmsDBEntities : DbContext
    {
        public CmsDBEntities()
            : base("name=CmsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminRegister> AdminRegister { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<UserRegister> UserRegister { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Pay> Pay { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
    }
}
