//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int OrderDetailsId { get; set; }
        public Nullable<int> orderid { get; set; }
        public Nullable<int> courseid { get; set; }
        public string coursename { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
