//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public int EnrollId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CourseName { get; set; }
        public Nullable<decimal> CoursePrice { get; set; }
        public Nullable<System.DateTime> EnrollDate { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
